---

- name: Configure firewall services
  firewalld:
    service: "{{ item }}"
    immediate: true
    permanent: true
    zone: public
    state: enabled
  with_items:
    - "{{ spacewalk_firewall.services }}"
  when: firewalld_enabled
  tags:
    - firewall

- name: Configure firewall ports
  firewalld:
    port: "{{ item }}"
    immediate: true
    permanent: true
    zone: public
    state: enabled
  with_items:
    - "{{ spacewalk_firewall.ports }}"
  when: firewalld_enabled
  tags:
    - firewall

