---

- name: Subscribe to required channels
  import_role:
    name: spacewalk-client
    tasks_from: channel.yml
  vars:
    channels: '{{ spacewalk_rhn_channels }}'

- name: Install spacewalk packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ spacewalk_pkgs }}"
