---
# tasks file for spacewalk

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - el.yml

- include: install.yml
  tags: install

- include: configure.yml
  tags: configure

- include: setup.yml
  tags: setup

- include: channels.yml
  tags: channels
